### ISSUE TITLE
Issues with .net framework project

### ISSUE THREAD

**Issue by teocomi** [getsentry/dotnet-assembly-alias#14]
Hey Simon, thanks a lot for this project - DLL hell is a very familiar issue, as [our project](https://github.com/specklesystems) has several plugins for various applications.

We've successfully used Alias on a .net standard project ([this one](https://github.com/specklesystems/speckle-sharp/tree/main/Core) called `Core`), but we're running into issues when running it on a .net framework project ([this one](https://github.com/specklesystems/speckle-sharp/tree/main/ConnectorRevit/ConnectorRevit2023), for example, which actually references Core).

Are there any known limitations with .net framework?

Curiously, the error I'm getting is thrown when the `ModuleReaaderWriter` is processing `Sentry.dll` (reference in Core) and it complains that "System.dll" is not found, as a matter of fact, it's not present in the bin folder, but afaik it is not needed there. 

If you'd like to reproduce it yourself, you need to:
- build [this project](https://github.com/specklesystems/speckle-sharp/blob/main/ConnectorRevit/ConnectorRevit2023/ConnectorRevit2023.csproj)
- use [my Fork](https://github.com/teocomi/dotnet-assembly-alias) so it can properly exclude some mixed code assemblies (will improve my PR soon!)
- run it with `--target-directory "[...]\bin\Debug" --suffix _Speckle --assemblies-to-alias "Serilog*" --assemblies-to-exclude "lib*;e_sqlite*;Tmds*;Revit*"`

I tried manually copying `System.dll` in the bin folder, and this made Alias run correctly, but we got other exceptions about methods missing when running our plugin.

**Comment by janis-veinbergs** [comment]
Got same issue when trying to Alias .net462 assembly. System.dll not found.

Is this tool designed to support legacy .NET Framework projects?
